
import { CurrencyRate, MetalRate, AppConfig, CryptoRate } from './types.ts';

export const TRANSLATIONS_INITIAL = {
  ku: {
    currencies: "دراوەکان",
    metals: "کانزاکان",
    converter: "بژمێر",
    settings: "ڕێکخستنەکان",
    last_update: "نوێکردنەوە",
    headlines: "هەواڵەکان",
    market_local: "ناوخۆ",
    market_transfer: "حەواڵە",
    market_toman: "تمەن",
    market_global: "جیهانی",
    metal_gold: "زێڕ",
    metal_silver: "زیو",
    metal_global: "بۆرسە",
    name_code: "جۆر",
    sell: "فرۆشتن",
    buy: "کڕین",
    no_data: "هیچ نرخێک نییە",
    amount: "بڕ",
    from: "لە",
    to: "بۆ",
    login: "چوونەژوورەوە",
    logout: "دەرچوون",
    preferences: "ڕێکخستن",
    interface: "ڕووکار",
    language: "زمان",
    admin_dashboard: "بەڕێوەبردن",
    admin_title: "کۆنترۆڵ",
    admin_desc: "دەستکاری نرخ",
    developer_mode: "گەشەپێدەر",
    back: "گەڕانەوە",
    save: "پاشەکەوت",
    dark: "تاریک",
    light: "ڕووناک",
    system: "سیستەم",
    paper: "کاغەزی",
    market_note: "ئەم نرخانە تەنها بۆ زانیارییە.",
    rate: "نرخ",
    users: "بەکارهێنەران",
    appearance: "ڕووکار",
    font_family: "فۆنت",
    table_view: "خشتە",
    grid_view: "تۆڕ",
    terminal: "تێرمیناڵ",
    ui_colors: "ڕەنگەکان",
    copied: "کۆپی کرا",
    copy: "کۆپی",
    share: "ناردن",
    estimated_result: "ئەنجامی خەمڵێنراو",
    email: "ناوی بەکارهێنەر",
    password: "وشەی نهێنی",
    crypto: "دراوە ئەلیکترۆنییەکان",
    price: "نرخ",
    change_24h: "گۆڕانکاری ٢٤ کاتژمێر",
    login_secure_terminal: "تێرمیناڵی پارێزراوی چوونەژوورەوە",
    login_join_network: "بەشداربە لە تۆڕەکە",
    login_name_label: "ناو",
    login_name_placeholder: "ناوەکەت بنووسە...",
    login_username_placeholder: "ناوی بەکارهێنەر...",
    login_password_placeholder: "••••••••",
    login_create_account: "هەژمار دروست بکە",
    login_authenticate: "چوونەژوورەوە",
    login_request_access: "داوای بەشداریکردن بکە",
    login_already_have_account: "پێشتر هەژمارم هەیە",
    accounts: "هەژمارەکان",
    transactions: "مامەڵەکان",
    inventory: "کۆگا",
    pos: "فرۆشتن",
    total_spending: "کۆی خەرجییەکان",
    total_income: "کۆی داهات",
    profit_loss: "قازانج/زیان",
    add_transaction: "زیادکردنی مامەڵە",
    add_product: "زیادکردنی کاڵا",
    item_name: "ناوی کاڵا",
    transaction_type: "جۆری مامەڵە",
    quantity: "دانە",
    price_per_item: "نرخی تاک",
    total: "کۆی گشتی",
    profit: "قازانج",
    image_optional: "وێنە (ئارەزوومەندانە)",
    note_optional: "تێبینی (ئارەزوومەندانە)",
    customer_name: "ناوی کڕیار",
    status: "بارودۆخ",
    due_date: "بەرواری شایستە",
    expense: "خەرجی",
    rent: "کرێ",
    paid: "دراوە",
    debt: "قەرز",
    register: "تۆمارکردن",
    transaction_list: "لیستی مامەڵەکان",
    no_transactions: "هیچ مامەڵەیەک تۆمار نەکراوە",
    inventory_actions: "کارەکانی کۆگا",
    close: "داخستن",
    add_new_product: "زیادکردنی کاڵای نوێ",
    edit_product: "دەستکاری کاڵا",
    basic: "سەرەتایی",
    advanced: "پێشکەوتوو",
    product_barcode: "بارکۆدی کاڵا",
    product_name: "ناوی کاڵا",
    category: "بەش",
    cost_price: "تێچوو",
    selling_price: "نرخی فرۆشتن",
    product_quantity: "دانەی کاڵا",
    expiry_date: "بەرواری بەسەرچوون",
    wholesale_price: "نرخی جوملە",
    product_link: "لینکی کاڵا",
    product_note: "تێبینی کاڵا",
    update_product: "نوێکردنەوەی کاڵا",
    products_grid: "تۆڕی کاڵاکان",
    no_products: "هیچ کاڵایەک زیاد نەکراوە",
    pos_products: "کاڵاکانی فرۆشتن",
    search_product: "گەڕان بۆ کاڵا",
    all_categories: "هەموو بەشەکان",
    cart: "سەبەتە",
    add_to_cart: "زیادکردن بۆ سەبەتە",
    empty_cart: "سەبەتە بەتاڵە",
    checkout: "پارەدان",
    manage_categories: "بەڕێوەبردنی بەشەکان",
    new_category_name: "ناوی بەشی نوێ",
    no_categories: "هیچ بەشێک زیاد نەکراوە",
    edit: "دەستکاری",
    delete: "سڕینەوە",
    confirm_delete: "دڵنیای لە سڕینەوە؟",
    mark_as_paid: "نیشانەکردن وەک دراو",
    print: "چاپکردن",
    login_title: "Golden Exchange",
    reports: "ڕاپۆرتەکان",
    customers: "کڕیارەکان",
    low_stock: "کۆگای کەم",
    expired: "بەسەرچوو",
    export_csv: "داگرتنی CSV",
    debt_summary: "کۆی قەرزەکان",
    total_debt: "کۆی گشتی قەرز",
    customer_transactions: "مامەڵەکانی کڕیار",
    stock_alerts: "ئاگادارییەکانی کۆگا",
    monthly_report: "ڕاپۆرتی مانگانە",
    weekly_report: "ڕاپۆرتی هەفتانە",
    daily_report: "ڕاپۆرتی ڕۆژانە",
    total_profit: "کۆی قازانج",
    total_loss: "کۆی زیان",
    customer_list: "لیستی کڕیارەکان"
  },
  ar: {
    login_title: "Golden Exchange",
    currencies: "العملات",
    metals: "المعادن",
    converter: "المحول",
    settings: "الإعدادات",
    last_update: "التحديث",
    market_local: "المحلي",
    market_transfer: "الحوالات",
    market_toman: "التومان",
    market_global: "العالمي",
    metal_gold: "الذهب",
    metal_silver: "الفضة",
    sell: "بيع",
    buy: "شراء",
    save: "حفظ",
    email: "اسم المستخدم",
    password: "كلمة المرور",
    crypto: "العملات الرقمية",
    price: "السعر",
    change_24h: "تغيير 24 ساعة"
  },
  en: {
    currencies: "Currencies",
    metals: "Metals",
    converter: "Converter",
    settings: "Settings",
    last_update: "Update",
    market_local: "Local",
    market_global: "Global",
    sell: "Sell",
    buy: "Buy",
    save: "Save",
    email: "Username",
    password: "Password",
    crypto: "Crypto",
    price: "Price",
    change_24h: "24h Change"
  }
};

export const DEFAULT_CONFIG: AppConfig = {
  appName: 'Golden exchange',
  primaryColor: '#D4AF37', // Gold color
  secondaryColor: '#0f172a',
  backgroundColor: '#f8fafc',
  cardColor: '#ffffff',
  textColor: '#0f172a',
  borderRadius: 12,
  fontSize: 12,
  fontFamily: 'Noto Sans Arabic',
  layoutMode: 'table',
  notificationsEnabled: false,
  translations: TRANSLATIONS_INITIAL
};

export const INITIAL_RATES: CurrencyRate[] = [
  // --- LOCAL IRAQ ---
  { id: 'l1', name: 'دۆلار - بەغدا', code: 'USD/IQD', symbol: 'IQD', buy: 151250, sell: 151750, change24h: 0.15, lastUpdated: new Date().toISOString(), change: 'up', flag: 'https://flagcdn.com/w80/iq.png', category: 'local' },
  { id: 'l2', name: 'دۆلار - هەولێر', code: 'USD/IQD', symbol: 'IQD', buy: 151300, sell: 151800, change24h: 0.20, lastUpdated: new Date().toISOString(), change: 'up', flag: 'https://flagcdn.com/w80/iq.png', category: 'local' },
  { id: 'l3', name: 'دۆلار - سلێمانی', code: 'USD/IQD', symbol: 'IQD', buy: 151250, sell: 151750, change24h: 0.18, lastUpdated: new Date().toISOString(), change: 'up', flag: 'https://flagcdn.com/w80/iq.png', category: 'local' },
  { id: 'l4', name: 'دۆلار - کەرکووک', code: 'USD/IQD', symbol: 'IQD', buy: 151200, sell: 151700, change24h: 0.10, lastUpdated: new Date().toISOString(), change: 'up', flag: 'https://flagcdn.com/w80/iq.png', category: 'local' },
  { id: 'l5', name: 'دۆلار - بەسرە', code: 'USD/IQD', symbol: 'IQD', buy: 151200, sell: 151700, change24h: 0.12, lastUpdated: new Date().toISOString(), change: 'up', flag: 'https://flagcdn.com/w80/iq.png', category: 'local' },
  { id: 'l6', name: 'دۆلار - دهۆک', code: 'USD/IQD', symbol: 'IQD', buy: 151300, sell: 151800, change24h: 0.20, lastUpdated: new Date().toISOString(), change: 'up', flag: 'https://flagcdn.com/w80/iq.png', category: 'local' },
  { id: 'l7', name: 'دۆلار - نەجەف', code: 'USD/IQD', symbol: 'IQD', buy: 151250, sell: 151750, change24h: 0.15, lastUpdated: new Date().toISOString(), change: 'up', flag: 'https://flagcdn.com/w80/iq.png', category: 'local' },
  { id: 'l8', name: 'دۆلار - مووسڵ', code: 'USD/IQD', symbol: 'IQD', buy: 151250, sell: 151750, change24h: 0.15, lastUpdated: new Date().toISOString(), change: 'up', flag: 'https://flagcdn.com/w80/iq.png', category: 'local' },
  { id: 'l9', name: 'دۆلار - کەربەلا', code: 'USD/IQD', symbol: 'IQD', buy: 151250, sell: 151750, change24h: 0.15, lastUpdated: new Date().toISOString(), change: 'up', flag: 'https://flagcdn.com/w80/iq.png', category: 'local' },
  { id: 'l10', name: 'دۆلار - ناسریە', code: 'USD/IQD', symbol: 'IQD', buy: 151200, sell: 151700, change24h: 0.12, lastUpdated: new Date().toISOString(), change: 'up', flag: 'https://flagcdn.com/w80/iq.png', category: 'local' },
  { id: 'gold_usd_21', name: 'زێڕی عەیارە ٢١ (Mithqal)', code: '21K/USD', symbol: '$', buy: 386.20, sell: 388.20, change24h: 0.7, lastUpdated: new Date().toISOString(), change: 'up', flag: 'https://cdn-icons-png.flaticon.com/512/2536/2536128.png', category: 'local' },

  // --- TOMAN ---
  { id: 'tm1', name: 'تمەن بۆ دینار (ملیۆن)', code: 'IRR/IQD', symbol: 'IQD', buy: 18250, sell: 18500, change24h: 0.5, lastUpdated: new Date().toISOString(), change: 'up', flag: 'https://flagcdn.com/w80/ir.png', category: 'toman' },
  { id: 'tm2', name: 'تمەن - تاران', code: 'USD/IRR', symbol: 'IRR', buy: 83000, sell: 84000, change24h: 0.8, lastUpdated: new Date().toISOString(), change: 'up', flag: 'https://flagcdn.com/w80/ir.png', category: 'toman' },

  // --- GLOBAL ---
  { id: 'g1', name: 'یۆرۆ بۆ دینار', code: 'EUR/IQD', symbol: 'IQD', buy: 159000, sell: 160500, change24h: 0.2, lastUpdated: new Date().toISOString(), change: 'up', flag: 'https://flagcdn.com/w80/eu.png', category: 'global' },
  { id: 'g2', name: 'پاوەند بۆ دینار', code: 'GBP/IQD', symbol: 'IQD', buy: 189500, sell: 191000, change24h: 0.3, lastUpdated: new Date().toISOString(), change: 'up', flag: 'https://flagcdn.com/w80/gb.png', category: 'global' },
  { id: 'g3', name: 'لیرەی تورکی بۆ دینار', code: 'TRY/IQD', symbol: 'IQD', buy: 4300, sell: 4450, change24h: 0.1, lastUpdated: new Date().toISOString(), change: 'up', flag: 'https://flagcdn.com/w80/tr.png', category: 'global' },
  { id: 'g4', name: 'درهەمی ئیماراتی بۆ دینار', code: 'AED/IQD', symbol: 'IQD', buy: 41000, sell: 41200, change24h: 0.1, lastUpdated: new Date().toISOString(), change: 'up', flag: 'https://flagcdn.com/w80/ae.png', category: 'global' },
  { id: 'g5', name: 'ڕیاڵی سعوودی بۆ دینار', code: 'SAR/IQD', symbol: 'IQD', buy: 40200, sell: 40350, lastUpdated: new Date().toISOString(), change: 'up', flag: 'https://flagcdn.com/w80/sa.png', category: 'global' },
  { id: 'g6', name: 'دیناری کوەیتی بۆ دینار', code: 'KWD/IQD', symbol: 'IQD', buy: 490000, sell: 492000, lastUpdated: new Date().toISOString(), change: 'up', flag: 'https://flagcdn.com/w80/kw.png', category: 'global' }
];

export const INITIAL_METALS: MetalRate[] = [
  // --- GLOBAL BULLION (USD) ---
  { id: 'm_xau', name: 'ئۆنسەی زێڕ (Global Gold)', code: 'XAU/USD', unit: '$', buy: 2745.50, sell: 2746.00, change24h: 0.45, lastUpdated: new Date().toISOString(), change: 'up', category: 'global', icon: 'https://cdn-icons-png.flaticon.com/512/261/261917.png' },
  { id: 'm_xag', name: 'ئۆنسەی زیو (Global Silver)', code: 'XAG/USD', unit: '$', buy: 34.65, sell: 34.70, change24h: 1.2, lastUpdated: new Date().toISOString(), change: 'up', category: 'global', icon: 'https://cdn-icons-png.flaticon.com/512/2415/2415255.png' },
];

export const INITIAL_CRYPTO: CryptoRate[] = [
  { id: 'c1', name: 'Bitcoin', symbol: 'BTC', price: 96450.20, change24h: 2.5, lastUpdated: new Date().toISOString(), icon: 'https://cryptologos.cc/logos/bitcoin-btc-logo.png' },
  { id: 'c2', name: 'Ethereum', symbol: 'ETH', price: 2745.15, change24h: -1.2, lastUpdated: new Date().toISOString(), icon: 'https://cryptologos.cc/logos/ethereum-eth-logo.png' },
  { id: 'c3', name: 'Tether', symbol: 'USDT', price: 1.00, change24h: 0.01, lastUpdated: new Date().toISOString(), icon: 'https://cryptologos.cc/logos/tether-usdt-logo.png' },
  { id: 'c4', name: 'Solana', symbol: 'SOL', price: 185.40, change24h: 5.8, lastUpdated: new Date().toISOString(), icon: 'https://cryptologos.cc/logos/solana-sol-logo.png' },
  { id: 'c5', name: 'Binance Coin', symbol: 'BNB', price: 612.30, change24h: 0.5, lastUpdated: new Date().toISOString(), icon: 'https://cryptologos.cc/logos/bnb-bnb-logo.png' },
  { id: 'c6', name: 'XRP', symbol: 'XRP', price: 2.45, change24h: -3.2, lastUpdated: new Date().toISOString(), icon: 'https://cryptologos.cc/logos/xrp-xrp-logo.png' },
  { id: 'c7', name: 'Cardano', symbol: 'ADA', price: 0.85, change24h: 1.4, lastUpdated: new Date().toISOString(), icon: 'https://cryptologos.cc/logos/cardano-ada-logo.png' },
  { id: 'c8', name: 'Dogecoin', symbol: 'DOGE', price: 0.38, change24h: 12.5, lastUpdated: new Date().toISOString(), icon: 'https://cryptologos.cc/logos/dogecoin-doge-logo.png' },
  { id: 'c9', name: 'Polkadot', symbol: 'DOT', price: 7.20, change24h: -0.8, lastUpdated: new Date().toISOString(), icon: 'https://cryptologos.cc/logos/polkadot-new-dot-logo.png' },
  { id: 'c10', name: 'Chainlink', symbol: 'LINK', price: 18.50, change24h: 2.1, lastUpdated: new Date().toISOString(), icon: 'https://cryptologos.cc/logos/chainlink-link-logo.png' },
];
